// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Mark Pickering and PICKBITS LLC. Part of PickBits File Share.
import { mkdir, writeFile } from 'node:fs/promises';
import { pathToFileURL } from 'node:url';
import { loadConfig } from '../scripts/config.mjs';
import { configEnvironment } from '../lib/config.mjs';
export function buildTemplates(config) {
const origin = `https://${config.domain}`;
const ref = name => ({Ref:name});
const att = (name,key) => ({'Fn::GetAtt':[name,key]});
const sub = value => ({'Fn::Sub':value});
const resource=(Type,Properties,extra={})=>({Type,Properties,...extra});
const retain={DeletionPolicy:'RetainExceptOnCreate',UpdateReplacePolicy:'Retain'};
const block={BlockPublicAcls:true,BlockPublicPolicy:true,IgnorePublicAcls:true,RestrictPublicBuckets:true};
const encrypt={ServerSideEncryptionConfiguration:[{ServerSideEncryptionByDefault:{SSEAlgorithm:'AES256'}}]};
const tags=[{Key:'Application',Value:'PickBits File Share'},{Key:'Purpose',Value:'Private file sharing'}];
const certificate={AWSTemplateFormatVersion:'2010-09-09',Description:'PickBits File Share HTTPS certificate',Resources:{Certificate:resource('AWS::CertificateManager::Certificate',{DomainName:config.domain,ValidationMethod:'DNS',DomainValidationOptions:[{DomainName:config.domain,HostedZoneId:config.hostedZoneId}],Tags:tags})},Outputs:{CertificateArn:{Value:ref('Certificate')}}};
const resources={
  EmailIdentity:resource('AWS::SES::EmailIdentity',{EmailIdentity:config.sesFromAddress}),
  WebBucket:resource('AWS::S3::Bucket',{PublicAccessBlockConfiguration:block,BucketEncryption:encrypt,OwnershipControls:{Rules:[{ObjectOwnership:'BucketOwnerEnforced'}]},Tags:tags},retain),
  FilesBucket:resource('AWS::S3::Bucket',{PublicAccessBlockConfiguration:block,BucketEncryption:encrypt,OwnershipControls:{Rules:[{ObjectOwnership:'BucketOwnerEnforced'}]},VersioningConfiguration:{Status:'Enabled'},CorsConfiguration:{CorsRules:[{AllowedOrigins:[origin],AllowedMethods:['GET','HEAD','POST'],AllowedHeaders:['*'],ExposedHeaders:['ETag'],MaxAge:300}]},LifecycleConfiguration:{Rules:[{Id:'Remove-abandoned-staging',Status:'Enabled',Prefix:'staging/',ExpirationInDays:1,NoncurrentVersionExpiration:{NoncurrentDays:1},AbortIncompleteMultipartUpload:{DaysAfterInitiation:1}}]},Tags:tags},retain),
  Table:resource('AWS::DynamoDB::Table',{BillingMode:'PAY_PER_REQUEST',AttributeDefinitions:[{AttributeName:'pk',AttributeType:'S'},{AttributeName:'sk',AttributeType:'S'}],KeySchema:[{AttributeName:'pk',KeyType:'HASH'},{AttributeName:'sk',KeyType:'RANGE'}],TimeToLiveSpecification:{AttributeName:'expiresAt',Enabled:true},PointInTimeRecoverySpecification:{PointInTimeRecoveryEnabled:true},SSESpecification:{SSEEnabled:true},Tags:tags},retain),
  UserPool:resource('AWS::Cognito::UserPool',{UserPoolName:`${config.stackName}-private`,UsernameAttributes:['email'],UsernameConfiguration:{CaseSensitive:false},AutoVerifiedAttributes:['email'],AdminCreateUserConfig:{AllowAdminCreateUserOnly:true,InviteMessageTemplate:{EmailSubject:'Your invitation to PickBits File Share',EmailMessage:`You have been invited to PickBits File Share, a private space for your files.<br/><br/>Sign in at <a href="${origin}">${origin}</a><br/>Email: {username}<br/>Temporary password: {####}<br/><br/>You will choose a new password when you first sign in. This invitation expires in 7 days.<br/><br/>Made with PickBits File Share.`}},Policies:{PasswordPolicy:{MinimumLength:14,RequireLowercase:true,RequireUppercase:true,RequireNumbers:true,RequireSymbols:true,TemporaryPasswordValidityDays:7}},AccountRecoverySetting:{RecoveryMechanisms:[{Name:'verified_email',Priority:1}]},MfaConfiguration:'OPTIONAL',EnabledMfas:['SOFTWARE_TOKEN_MFA'],UserPoolTags:{Application:'PickBits File Share'}},retain),
  Owners:resource('AWS::Cognito::UserPoolGroup',{UserPoolId:ref('UserPool'),GroupName:'owners',Description:'Can invite new PickBits File Share members'}),
  UserPoolClient:resource('AWS::Cognito::UserPoolClient',{UserPoolId:ref('UserPool'),ClientName:`${config.stackName}-web`,GenerateSecret:false,AllowedOAuthFlowsUserPoolClient:true,AllowedOAuthFlows:['code'],AllowedOAuthScopes:['openid','email','profile'],CallbackURLs:[`${origin}/api/auth/callback`],LogoutURLs:[origin],SupportedIdentityProviders:['COGNITO'],PreventUserExistenceErrors:'ENABLED',EnableTokenRevocation:true,AccessTokenValidity:15,IdTokenValidity:15,RefreshTokenValidity:1,TokenValidityUnits:{AccessToken:'minutes',IdToken:'minutes',RefreshToken:'days'},ExplicitAuthFlows:['ALLOW_REFRESH_TOKEN_AUTH']}),
  UserPoolDomain:resource('AWS::Cognito::UserPoolDomain',{UserPoolId:ref('UserPool'),Domain:sub(config.stackName+'-${AWS::AccountId}-${AWS::Region}')}),
  ApiRole:resource('AWS::IAM::Role',{AssumeRolePolicyDocument:{Version:'2012-10-17',Statement:[{Effect:'Allow',Principal:{Service:'lambda.amazonaws.com'},Action:'sts:AssumeRole'}]},Policies:[{PolicyName:`${config.stackName}-data`,PolicyDocument:{Version:'2012-10-17',Statement:[{Effect:'Allow',Action:['dynamodb:GetItem','dynamodb:PutItem','dynamodb:UpdateItem','dynamodb:DeleteItem','dynamodb:Query','dynamodb:TransactWriteItems'],Resource:att('Table','Arn')},{Effect:'Allow',Action:['s3:GetObject','s3:PutObject','s3:DeleteObject'],Resource:sub('${FilesBucket.Arn}/*')},{Effect:'Allow',Action:['cognito-idp:AdminGetUser','cognito-idp:AdminCreateUser'],Resource:att('UserPool','Arn')},{Effect:'Allow',Action:['ses:SendEmail','ses:SendRawEmail'],Resource:sub('arn:aws:ses:${AWS::Region}:${AWS::AccountId}:identity/'+config.sesFromAddress)},{Effect:'Allow',Action:['logs:CreateLogStream','logs:PutLogEvents'],Resource:sub('arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/'+config.stackName+'-api:*')}]}}],Tags:tags}),
  ApiLogs:resource('AWS::Logs::LogGroup',{LogGroupName:`/aws/lambda/${config.stackName}-api`,RetentionInDays:14}),
  Api:resource('AWS::Lambda::Function',{FunctionName:`${config.stackName}-api`,Runtime:'nodejs22.x',Handler:'index.handler',Role:att('ApiRole','Arn'),MemorySize:256,Timeout:30,ReservedConcurrentExecutions:5,Architectures:['arm64'],Environment:{Variables:{TABLE_NAME:ref('Table'),FILES_BUCKET:ref('FilesBucket'),USER_POOL_ID:ref('UserPool'),CLIENT_ID:ref('UserPoolClient'),COGNITO_DOMAIN:sub('${UserPoolDomain}.auth.${AWS::Region}.amazoncognito.com'),...configEnvironment(config)}},Code:{ZipFile:'exports.handler = async () => ({statusCode:503,body:"PickBits File Share is being prepared."});'},Tags:tags},{DependsOn:['ApiLogs']}),
  ApiUrl:resource('AWS::Lambda::Url',{TargetFunctionArn:ref('Api'),AuthType:'AWS_IAM'}),
  WebOac:resource('AWS::CloudFront::OriginAccessControl',{OriginAccessControlConfig:{Name:`${config.stackName}-web`,OriginAccessControlOriginType:'s3',SigningBehavior:'always',SigningProtocol:'sigv4'}}),
  ApiOac:resource('AWS::CloudFront::OriginAccessControl',{OriginAccessControlConfig:{Name:`${config.stackName}-api`,OriginAccessControlOriginType:'lambda',SigningBehavior:'always',SigningProtocol:'sigv4'}}),
  SecurityHeaders:resource('AWS::CloudFront::ResponseHeadersPolicy',{ResponseHeadersPolicyConfig:{Name:`${config.stackName}-security`,SecurityHeadersConfig:{ContentTypeOptions:{Override:true},FrameOptions:{FrameOption:'DENY',Override:true},ReferrerPolicy:{ReferrerPolicy:'no-referrer',Override:true},StrictTransportSecurity:{AccessControlMaxAgeSec:31536000,IncludeSubdomains:true,Preload:false,Override:true},ContentSecurityPolicy:{ContentSecurityPolicy:`default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob: https://*.s3.${config.region}.amazonaws.com; media-src 'self' blob: https://*.s3.${config.region}.amazonaws.com; connect-src 'self' https://*.s3.${config.region}.amazonaws.com; frame-src 'self' blob:; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'none'`,Override:true}},CustomHeadersConfig:{Items:[{Header:'Permissions-Policy',Value:'camera=(), microphone=(), geolocation=()',Override:true}]}}}),
  Distribution:resource('AWS::CloudFront::Distribution',{DistributionConfig:{Enabled:true,Comment:'PickBits File Share private file workspace',Aliases:[config.domain],DefaultRootObject:'index.html',HttpVersion:'http2and3',IPV6Enabled:true,PriceClass:'PriceClass_100',Origins:[{Id:'web',DomainName:att('WebBucket','RegionalDomainName'),OriginAccessControlId:ref('WebOac'),S3OriginConfig:{OriginAccessIdentity:''}},{Id:'api',DomainName:{'Fn::Select':[2,{'Fn::Split':['/',att('ApiUrl','FunctionUrl')]}]},OriginAccessControlId:ref('ApiOac'),CustomOriginConfig:{OriginProtocolPolicy:'https-only',OriginSSLProtocols:['TLSv1.2']}}],DefaultCacheBehavior:{TargetOriginId:'web',ViewerProtocolPolicy:'redirect-to-https',AllowedMethods:['GET','HEAD'],Compress:true,CachePolicyId:'658327ea-f89d-4fab-a63d-7e88639e58f6',ResponseHeadersPolicyId:ref('SecurityHeaders')},CacheBehaviors:[{PathPattern:'/api/*',TargetOriginId:'api',ViewerProtocolPolicy:'https-only',AllowedMethods:['GET','HEAD','OPTIONS','PUT','PATCH','POST','DELETE'],CachePolicyId:'4135ea2d-6df8-44a3-9df3-4b5a84be39ad',OriginRequestPolicyId:'b689b0a8-53d0-40ab-baf2-68738e2966ac',ResponseHeadersPolicyId:ref('SecurityHeaders')}],ViewerCertificate:{AcmCertificateArn:ref('CertificateArn'),SslSupportMethod:'sni-only',MinimumProtocolVersion:'TLSv1.2_2021'}},Tags:tags}),
  WebPolicy:resource('AWS::S3::BucketPolicy',{Bucket:ref('WebBucket'),PolicyDocument:{Version:'2012-10-17',Statement:[{Effect:'Allow',Principal:{Service:'cloudfront.amazonaws.com'},Action:'s3:GetObject',Resource:sub('${WebBucket.Arn}/*'),Condition:{StringEquals:{'AWS:SourceArn':sub('arn:aws:cloudfront::${AWS::AccountId}:distribution/${Distribution}')}}},{Effect:'Deny',Principal:'*',Action:'s3:*',Resource:[att('WebBucket','Arn'),sub('${WebBucket.Arn}/*')],Condition:{Bool:{'aws:SecureTransport':'false'}}}]}}),
  FilesPolicy:resource('AWS::S3::BucketPolicy',{Bucket:ref('FilesBucket'),PolicyDocument:{Version:'2012-10-17',Statement:[{Effect:'Deny',Principal:'*',Action:'s3:*',Resource:[att('FilesBucket','Arn'),sub('${FilesBucket.Arn}/*')],Condition:{Bool:{'aws:SecureTransport':'false'}}}]}}),
  ApiPermissionUrl:resource('AWS::Lambda::Permission',{FunctionName:ref('Api'),Action:'lambda:InvokeFunctionUrl',Principal:'cloudfront.amazonaws.com',SourceArn:sub('arn:aws:cloudfront::${AWS::AccountId}:distribution/${Distribution}')}),
  ApiPermissionInvoke:resource('AWS::Lambda::Permission',{FunctionName:ref('Api'),Action:'lambda:InvokeFunction',Principal:'cloudfront.amazonaws.com',SourceArn:sub('arn:aws:cloudfront::${AWS::AccountId}:distribution/${Distribution}')}),
  Dns:resource('AWS::Route53::RecordSetGroup',{HostedZoneId:config.hostedZoneId,RecordSets:['A','AAAA'].map(Type=>({Name:config.domain,Type,AliasTarget:{DNSName:att('Distribution','DomainName'),HostedZoneId:'Z2FDTNDATAQYW2',EvaluateTargetHealth:false}}))}),
};
const template={AWSTemplateFormatVersion:'2010-09-09',Description:'PickBits File Share invitation-only file sharing on AWS',Parameters:{CertificateArn:{Type:'String'}},Resources:resources,Outputs:{WebBucket:{Value:ref('WebBucket')},FilesBucket:{Value:ref('FilesBucket')},TableName:{Value:ref('Table')},UserPoolId:{Value:ref('UserPool')},ClientId:{Value:ref('UserPoolClient')},CognitoDomain:{Value:sub('${UserPoolDomain}.auth.${AWS::Region}.amazoncognito.com')},DistributionId:{Value:ref('Distribution')},ApiFunction:{Value:ref('Api')},ApiUrl:{Value:att('ApiUrl','FunctionUrl')},URL:{Value:origin}}};
return { certificate, template };
}
export async function generateTemplates(config = loadConfig()) {
  const { certificate, template } = buildTemplates(config);
  const directory = new URL('./generated/', import.meta.url);
  await mkdir(directory, { recursive: true });
  await writeFile(new URL('certificate.json', directory), JSON.stringify(certificate, null, 2)+'\n');
  await writeFile(new URL('file-share.json', directory), JSON.stringify(template, null, 2)+'\n');
  console.log('Generated infra/generated/certificate.json and file-share.json.');
}
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) await generateTemplates();
