// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Mark Pickering and PICKBITS LLC. Part of PickBits File Share.
import test from 'node:test';
import assert from 'node:assert/strict';
import { PDFDocument } from 'pdf-lib';
import { createApi, hash } from '../server/api.mjs';

const ownerId='owner-123',memberId='member-456',png='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=';
async function fixturePdf(){const pdf=await PDFDocument.create();pdf.addPage([300,200]);return Buffer.from(await pdf.save());}
function harness({mailFrom='',mailReplyTo='',failSes=false}={}){
  const rows=new Map(),objects=new Map(),calls=[];const key=(pk,sk)=>`${pk}|${sk}`;const put=item=>rows.set(key(item.pk,item.sk),structuredClone(item));
  const users={owner:{id:ownerId,email:'avery@example.com',name:'Avery Rowan',admin:true},member:{id:memberId,email:'customer@example.com',name:'Customer',admin:false}};
  for(const [name,u] of Object.entries(users)){const raw=`session-${name}`;put({pk:`SESSION#${hash(raw)}`,sk:'SESSION',authenticatedAt:1,expiresAt:Math.floor(Date.now()/1000)+3600,username:u.email,user:u,...(u.admin?{mfaVersion:'test-mfa'}:{})});}
  put({pk:`USER#${ownerId}`,sk:'MFA',version:'test-mfa',secret:'JBSWY3DPEHPK3PXP',lastCounter:0});
  const db={async send(command){calls.push(command);const p=command.input;switch(command.constructor.name){case 'GetCommand':return {Item:rows.get(key(p.Key.pk,p.Key.sk))};case 'QueryCommand':return {Items:[...rows.values()].filter(r=>r.pk===p.ExpressionAttributeValues[':pk']&&r.sk.startsWith(p.ExpressionAttributeValues[':prefix']))};case 'PutCommand':put(p.Item);return {};case 'DeleteCommand':rows.delete(key(p.Key.pk,p.Key.sk));return {};case 'UpdateCommand':{const item=rows.get(key(p.Key.pk,p.Key.sk));if(item){for(const [n,v] of Object.entries(p.ExpressionAttributeValues||{})){const name=Object.entries(p.ExpressionAttributeNames||{}).find(([,value])=>value===n.slice(1))?.[0]?.slice(1)||n.slice(1);if(p.UpdateExpression.includes(`if_not_exists(${name}`)&&item[name]!==undefined)continue;item[name]=v;}put(item);}return {};};case 'TransactWriteCommand':for(const op of p.TransactItems){if(op.Put)put(op.Put.Item);if(op.Delete)rows.delete(key(op.Delete.Key.pk,op.Delete.Key.sk));}return {};default:throw new Error(command.constructor.name);}}};
  const cognito={async send(command){calls.push(command);if(command.constructor.name==='AdminGetUserCommand')return {Enabled:true};return {};}};const sesCalls=[];const ses={async send(command){sesCalls.push(command);if(failSes)throw new Error('SES transport details');return {};}};
  const s3={async send(command){calls.push(command);const p=command.input;if(command.constructor.name==='HeadObjectCommand'){const bytes=objects.get(p.Key);if(!bytes){const e=new Error('Not found');e.name='NotFound';throw e;}return {ContentLength:bytes.length};}if(command.constructor.name==='GetObjectCommand'){const bytes=objects.get(p.Key);if(!bytes)throw new Error(`Missing ${p.Key}`);return {Body:{transformToByteArray:async()=>bytes}};}if(command.constructor.name==='PutObjectCommand'){objects.set(p.Key,Buffer.from(p.Body));return {};}if(command.constructor.name==='DeleteObjectCommand'){objects.delete(p.Key);return {};}return {};}};
  const api=createApi({db,s3,cognito,ses,env:{TABLE_NAME:'test',USER_POOL_ID:'pool',CLIENT_ID:'client',APP_ORIGIN:'https://files.example.com',FILES_BUCKET:'bucket',MAIL_FROM:mailFrom,MAIL_REPLY_TO:mailReplyTo,TEAM_WORKSPACE_MEMBERS:'[]'},verifier:{verify(){throw new Error('Unused');}},signUrl:async(client,c)=>`https://example.com/signed/${c.input.Key}`,signPost:async()=>({url:'https://upload.example.com',fields:{}})});
  const request=(path,{method='GET',body,user='owner',authenticated=true,headers={}}={})=>api(new Request(`https://files.example.com/api${path}`,{method,headers:{...(authenticated?{Cookie:`__Host-pickbits-file-share_session=session-${user}`}:{ }),Origin:'https://files.example.com','Content-Type':'application/json','user-agent':'documents-test','x-forwarded-for':'198.51.100.10, 10.0.0.1',...headers},body:body===undefined?undefined:JSON.stringify(body)}));
  return {request,rows,objects,calls,sesCalls,users};
}
async function createDocument(h,{type='agreement',title='Pest service agreement',bytes=undefined}={}){bytes??=await fixturePdf();const r=await h.request('/documents/upload',{method:'POST',body:{title,type,recipientName:'Customer Name',recipientEmail:'customer@example.com',size:bytes.length,mime:'application/pdf'}});assert.equal(r.status,201);const upload=await r.json();h.objects.set(`docs/${upload.id}/original.pdf`,bytes);const complete=await h.request(`/documents/${upload.id}/complete`,{method:'POST',body:{}});assert.equal(complete.status,200);return {id:upload.id,bytes,doc:await complete.json()};}
async function ownerSign(h,id,body={consent:true,typedName:'Avery Rowan',signature:png}){return h.request(`/documents/${id}/sign`,{method:'POST',body});}
function tokenFromUrl(url){return new URL(url).hash.replace(/^#d=/,'');}

test('non-admin cannot create, void, list, or relink',async()=>{const h=harness();const made=await createDocument(h,{type:'receipt'});assert.equal((await h.request('/documents/upload',{method:'POST',user:'member',body:{title:'Nope',type:'receipt',recipientName:'x',recipientEmail:'x@example.com',size:1,mime:'application/pdf'}})).status,403);assert.equal((await h.request('/documents',{user:'member'})).status,403);assert.equal((await h.request(`/documents/${made.id}/void`,{method:'POST',user:'member',body:{}})).status,403);assert.equal((await h.request(`/documents/${made.id}/relink`,{method:'POST',user:'member',body:{}})).status,403);});
test('public routes work without a cookie and bad, expired, or voided links are 404',async()=>{const h=harness();const made=await createDocument(h,{type:'receipt'});const first=tokenFromUrl(made.doc.recipientUrl);assert.equal((await h.request(`/public/documents/${first}`,{authenticated:false})).status,200);assert.equal((await h.request(`/public/documents/not-a-real-token`,{authenticated:false})).status,404);h.rows.get(`DOCLINK#${hash(first)}|DOCLINK`).expiresAt=0;assert.equal((await h.request(`/public/documents/${first}`,{authenticated:false})).status,404);const fresh=await h.request(`/documents/${made.id}/relink`,{method:'POST',body:{}});const freshBody=await fresh.json(),freshToken=tokenFromUrl(freshBody.recipientUrl);assert.equal((await h.request(`/public/documents/${first}`,{authenticated:false})).status,404);assert.ok(freshBody.recipientUrl);await h.request(`/documents/${made.id}/void`,{method:'POST',body:{}});assert.equal((await h.request(`/public/documents/${freshToken}`,{authenticated:false})).status,404);});
test('relink invalidates old token and viewedAt is recorded only once',async()=>{const h=harness();const made=await createDocument(h,{type:'receipt'});const old=tokenFromUrl(made.doc.recipientUrl);const first=await h.request(`/public/documents/${old}`,{authenticated:false});const viewed=(await first.json()).viewedAt;assert.ok(viewed);assert.equal((await h.request(`/public/documents/${old}`,{authenticated:false})).status,200);assert.equal(h.calls.filter(c=>c.constructor.name==='UpdateCommand').length,1);await h.request(`/documents/${made.id}/relink`,{method:'POST',body:{}});assert.equal((await h.request(`/public/documents/${old}`,{authenticated:false})).status,404);});
test('recipient cannot sign before owner, validation is enforced, and cannot sign twice',async()=>{const h=harness();const made=await createDocument(h);const absent='a'.repeat(43);assert.equal((await h.request(`/public/documents/${absent}/sign`,{method:'POST',authenticated:false,body:{consent:true,typedName:'Customer',signature:png}})).status,404);assert.equal((await ownerSign(h,made.id,{consent:false,typedName:'Avery',signature:png})).status,400);assert.equal((await ownerSign(h,made.id,{consent:true,typedName:'',signature:png})).status,400);assert.equal((await ownerSign(h,made.id,{consent:true,typedName:'Avery',signature:'data:image/png;base64,not-png'})).status,400);const owner=await ownerSign(h,made.id);assert.equal(owner.status,200);const token=tokenFromUrl((await owner.clone().json()).recipientUrl);const done=await h.request(`/public/documents/${token}/sign`,{method:'POST',authenticated:false,body:{consent:true,typedName:'Customer Name',signature:png}});assert.equal(done.status,200);assert.equal((await h.request(`/public/documents/${token}/sign`,{method:'POST',authenticated:false,body:{consent:true,typedName:'Customer Name',signature:png}})).status,409);});
test('tampered original is refused, signed PDF has one appended page, matching hash, and recipient email text record',async()=>{const h=harness();const made=await createDocument(h);const owner=await ownerSign(h,made.id);const token=tokenFromUrl((await owner.clone().json()).recipientUrl);h.objects.set(`docs/${made.id}/original.pdf`,Buffer.from('%PDF-tampered'));assert.equal((await h.request(`/public/documents/${token}/sign`,{method:'POST',authenticated:false,body:{consent:true,typedName:'Customer Name',signature:png}})).status,409);h.objects.set(`docs/${made.id}/original.pdf`,made.bytes);const done=await h.request(`/public/documents/${token}/sign`,{method:'POST',authenticated:false,body:{consent:true,typedName:'Customer Name',signature:png}});assert.equal(done.status,200);const d=h.rows.get(`DOC#${made.id}|DOC`),signed=h.objects.get(`docs/${made.id}/signed.pdf`);assert.equal((await PDFDocument.load(signed)).getPageCount(),2);assert.equal(d.signedHash,hash(signed));assert.equal(d.signatures.at(-1).email,'customer@example.com');});
test('non-PDF is rejected at complete',async()=>{const h=harness();const bytes=Buffer.from('not a pdf');const r=await h.request('/documents/upload',{method:'POST',body:{title:'Bad file',type:'receipt',recipientName:'Customer',recipientEmail:'customer@example.com',size:bytes.length,mime:'application/pdf'}});const id=(await r.json()).id;h.objects.set(`docs/${id}/original.pdf`,bytes);assert.equal((await h.request(`/documents/${id}/complete`,{method:'POST',body:{}})).status,400);});
test('owner email endpoint sends the stored recipient a fresh link and escapes HTML',async()=>{const h=harness({mailFrom:'PickBits <owner@example.com>',mailReplyTo:'owner@example.com'});const made=await createDocument(h,{type:'receipt',title:'<script>alert(1)'});const old=tokenFromUrl(made.doc.recipientUrl);const sent=await h.request(`/admin/documents/${made.id}/email`,{method:'POST',body:{}});assert.equal(sent.status,200);const result=await sent.json(),fresh=tokenFromUrl(result.recipientUrl),command=h.sesCalls.at(-1);assert.notEqual(fresh,old);assert.deepEqual(command.input.Destination.ToAddresses,['customer@example.com']);assert.equal(command.input.Content.Simple.Subject.Data,'Your receipt from PickBits File Share: <script>alert(1)');assert.match(command.input.Content.Simple.Body.Html.Data,/&lt;script&gt;alert\(1\)/);assert.equal(result.emailCount,1);assert.ok(result.emailedAt);assert.equal((await h.request(`/public/documents/${old}`,{authenticated:false})).status,404);assert.equal((await h.request(`/public/documents/${fresh}`,{authenticated:false})).status,200);});
test('owner email endpoint requires owner and configured sender',async()=>{const noMail=harness();const made=await createDocument(noMail,{type:'invoice'});assert.equal((await noMail.request(`/admin/documents/${made.id}/email`,{method:'POST',body:{}})).status,503);assert.equal((await noMail.request(`/admin/documents/${made.id}/email`,{method:'POST',user:'member',body:{}})).status,403);});
test('recipient completion sends one raw email with the signed PDF to recipient and owner',async()=>{const h=harness({mailFrom:'PickBits <owner@example.com>',mailReplyTo:'owner@example.com'});const made=await createDocument(h);const owner=await ownerSign(h,made.id),token=tokenFromUrl((await owner.clone().json()).recipientUrl);const done=await h.request(`/public/documents/${token}/sign`,{method:'POST',authenticated:false,body:{consent:true,typedName:'Customer Name',signature:png}});assert.equal(done.status,200);assert.equal(h.sesCalls.length,1);const command=h.sesCalls[0],raw=Buffer.from(command.input.Content.Raw.Data).toString('utf8');assert.deepEqual(command.input.Destination.ToAddresses,['customer@example.com','owner@example.com']);assert.match(raw,/Subject: Signed: Pest service agreement/);assert.match(raw,/Content-Type: application\/pdf/);assert.match(raw,/Content-Disposition: attachment; filename="Pest service agreement - signed\.pdf"/);assert.match(raw,/Content-Transfer-Encoding: base64\r\nContent-Disposition/);assert.match(raw,/\r\n(?:[A-Za-z0-9+/]{76}\r\n)+/);});
test('SES completion failure does not block signing and is stored on the document',async()=>{const h=harness({mailFrom:'PickBits <owner@example.com>',mailReplyTo:'owner@example.com',failSes:true});const made=await createDocument(h);const owner=await ownerSign(h,made.id),token=tokenFromUrl((await owner.clone().json()).recipientUrl);const done=await h.request(`/public/documents/${token}/sign`,{method:'POST',authenticated:false,body:{consent:true,typedName:'Customer Name',signature:png}});assert.equal(done.status,200);assert.doesNotMatch(await done.text(),/SES transport details/);assert.equal(h.rows.get(`DOC#${made.id}|DOC`).completionEmailError,'SES transport details');});
