// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Mark Pickering and PICKBITS LLC. Part of PickBits File Share.
"use client";
import { useEffect, useRef, useState } from "react";
import { ArrowDownToLine, Check, Loader2, X } from "lucide-react";
import { api } from "@/lib/files";

type Summary = { businessName: string; title: string; type: "agreement" | "receipt" | "invoice"; status: string; recipientName?: string; ownerSignatureName?: string; ownerSignatureDate?: string; completedAt?: string; viewedAt?: string };

export default function RecipientDocument({ token }: { token: string }) {
  const [document,setDocument]=useState<Summary|null>(null);const [previewUrl,setPreviewUrl]=useState("");const [typedName,setTypedName]=useState("");const [consent,setConsent]=useState(false);const [signatureReady,setSignatureReady]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const canvas=useRef<HTMLCanvasElement>(null);const drawing=useRef(false);
  const load=async()=>{const d=await api<Summary>(`/public/documents/${token}`);setDocument(d);const signed=await api<{url:string}>(`/public/documents/${token}/pdf`);const response=await fetch(signed.url);if(!response.ok)throw new Error("The PDF preview could not be loaded.");const url=URL.createObjectURL(await response.blob());setPreviewUrl(old=>{if(old)URL.revokeObjectURL(old);return url;});};
  useEffect(()=>{load().catch(e=>setError((e as Error).message));},[token]);
  useEffect(()=>()=>{if(previewUrl)URL.revokeObjectURL(previewUrl);},[previewUrl]);
  const clear=()=>{const c=canvas.current;c?.getContext("2d")?.clearRect(0,0,c.width,c.height);setSignatureReady(false);};
  const start=(e:React.PointerEvent<HTMLCanvasElement>)=>{const c=canvas.current;if(!c)return;drawing.current=true;c.setPointerCapture(e.pointerId);const r=c.getBoundingClientRect(),ctx=c.getContext("2d")!;ctx.beginPath();ctx.moveTo((e.clientX-r.left)*c.width/r.width,(e.clientY-r.top)*c.height/r.height);};
  const draw=(e:React.PointerEvent<HTMLCanvasElement>)=>{if(!drawing.current)return;const c=canvas.current;if(!c)return;const r=c.getBoundingClientRect(),ctx=c.getContext("2d")!;ctx.lineWidth=3;ctx.lineCap="round";ctx.strokeStyle="#17253d";ctx.lineTo((e.clientX-r.left)*c.width/r.width,(e.clientY-r.top)*c.height/r.height);ctx.stroke();setSignatureReady(true);};
  const sign=async()=>{if(!consent||!typedName.trim()||!signatureReady)return;setBusy(true);setError("");try{const d=await api<Summary>(`/public/documents/${token}/sign`,{method:"POST",body:JSON.stringify({consent,typedName,signature:canvas.current?.toDataURL("image/png")})});setDocument(d);clear();const signed=await api<{url:string}>(`/public/documents/${token}/pdf`);const response=await fetch(signed.url);const url=URL.createObjectURL(await response.blob());setPreviewUrl(old=>{if(old)URL.revokeObjectURL(old);return url;});}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  const download=async()=>{try{location.assign((await api<{url:string}>(`/public/documents/${token}/pdf`)).url);}catch(e){setError((e as Error).message);}};
  return <main className="recipient-page"><header className="recipient-header"><a href="/" className="recipient-brand"><img src="/favicon.svg" alt=""/>PickBits File Share</a></header><section className="recipient-card">{error?<><h1>This link has expired or is no longer available.</h1><p className="recipient-error">{error}</p></>:!document?<Loader2 className="loading-spinner"/>:<><p className="recipient-eyebrow">DOCUMENT</p><h1>{document.title}</h1><p className="recipient-from">From {document.businessName}</p>{previewUrl?<iframe className="recipient-preview" title="PDF preview" src={previewUrl}/>:<div className="recipient-preview-loading"><Loader2 className="loading-spinner"/></div>}{document.status==="completed"?<><h2 className="recipient-signed"><Check size={20}/>Signed. Download your copy.</h2><button className="btn btn-primary" onClick={download}><ArrowDownToLine/>Download</button></>:document.type==="agreement"?<div className="recipient-sign"><label className="check-line"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>I agree to sign this electronically.</label><label className="field-label">Type your full name<input className="text-input" value={typedName} onChange={e=>setTypedName(e.target.value)} maxLength={200}/></label><label className="field-label">Draw your signature</label><canvas ref={canvas} className="signature-pad" width={600} height={160} onPointerDown={start} onPointerMove={draw} onPointerUp={()=>{drawing.current=false;}} onPointerCancel={()=>{drawing.current=false;}}/><div className="modal-actions"><button className="btn btn-secondary" onClick={clear}><X/>Clear</button><button className="btn btn-primary" disabled={busy||!consent||!typedName.trim()||!signatureReady} onClick={sign}>{busy?<Loader2 className="loading-spinner"/>:<Check/>}Sign</button></div><p className="recipient-copy">Your typed name and drawn signature count as your signature. You can download the signed copy right after.</p></div>:<button className="btn btn-primary" onClick={download}><ArrowDownToLine/>Download</button>}</>}</section><footer className="recipient-footer">The sender signed in their PickBits File Share account. The recipient signed using a private link sent to the email address shown.</footer></main>;
}
